project:
  type: website
  output-dir: docs

website:
  title: "Siyao Liu's Final HW"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Hobbies.qmd
        text: Hobbies

format:
  html:
    theme: vapor
    css: styles.css
    toc: true

editor: visual

